# Generated by Django 4.2.5 on 2023-09-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('release_date', models.DateField()),
                ('rating', models.FloatField()),
                ('image', models.ImageField(upload_to='products/')),
                ('manufacturer', models.CharField(max_length=255)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('warranty_duration', models.DurationField()),
                ('color', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('black', 'Black'), ('white', 'White')], max_length=10)),
                ('product_type', models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('appliances', 'Appliances'), ('books', 'Books')], max_length=255)),
            ],
        ),
    ]
